version: 1.1.{build}
image: Visual Studio 2022
configuration:
- Debug
- Release
platform:
- x86
- x64
clone_depth: 1

install:
- cmd: >-
    mkdir c:\downloads\npcap

    appveyor DownloadFile https://nmap.org/npcap/dist/npcap-sdk-1.06.zip -FileName c:\downloads\npcap\npcap.zip

    7z x c:\downloads\npcap\npcap.zip -y -oc:\projects\bsniffhub\msvs\lib\npcap\

- ps: (New-Object Net.WebClient).DownloadFile("https://master.dl.sourceforge.net/project/iup/3.32/Windows%20Libraries/Static/iup-3.32_Win32_vc17_lib.zip?viasf=1", "c:\downloads\iup\iup_x86.zip")
- ps: (New-Object Net.WebClient).DownloadFile("https://master.dl.sourceforge.net/project/iup/3.32/Windows%20Libraries/Static/iup-3.32_Win64_vc17_lib.zip?viasf=1", "c:\downloads\iup\iup_x64.zip")
- cmd: >-
    7z x c:\downloads\iup\iup_x86.zip -y -oc:\projects\bsniffhub\lib\iup\lib\Win32_vc15 iup.lib iupimglib.lib

    7z x c:\downloads\iup\iup_x64.zip -y -oc:\projects\bsniffhub\lib\iup\lib\Win64_vc15 iup.lib iupimglib.lib

build:
  project: c:\projects\bsniffhub\msvs\bsniffhub.sln
  verbosity: minimal
