language: c

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "v5+tJ+pdugUfxYgggWqg5uxSj6G+IfZSctyt+dpA+lJqn8upbPnRcvt/DztpwMzrpthp8nGU1tJyrU9scdRpVhI84fCj6kJb09A0KUYkdfuOXB65NJ5heFIg+KKa9R2NcDnnhJcJdzox2ly/8Ttk8EwUt5hRFoVxPyppl2WPwHzZ2mRA+MFfUWsPhy2d5JwK9vhv/U3PTEy7IXzsXu8ES5HNeAk/d7BbcStwYK11jUZpuX9O5Yrb3brPeNVhogFd2updlVTPGhyPocArNiLgMzpXj6Mrie2ZlmnTr564lBu9PbG7KV3wpxsIzlgfevwn1FntcJgKyudG2GdJjWoiMXSitUA3pAIhik2R6wRN3bzW4ev+9csC4rA13Hxv6kOnKGduuXcQXkQDdJX3jXCVwMUFg1Yu29GEzOPHygdMIhboS1REf/CG7NgzoXM4HYsHu2S9ugLR5ZICiWFi5AYpMViUglM1AHfn171b/srKxlGD43pY4KmRd14fjchpQKMc3GFt+H8cFyQwI5smXV77BRTaTaK46kD0kcDEv2qytq85xdxw3Da5s/qE6QORNbeCpGIsr7gqU7qs4ebFa0LbEhloPyW6WZ3GEheUYz41fRJKccH1NmuqlGcjXaCB1tPBePc/yw644Upa0dCQkjNncamMIGxj8SUSYL3icq3kfNs="
    # IUP packages
    # Linux44_64: xenial (x64) gcc 5.3
    # Linux415_64: bionic (x64) gcc 7.3
    # Linux54_64: focal (x64) gcc 9.3
    - IUP_XENIAL_URL='https://netactuate.dl.sourceforge.net/project/iup/3.30/Linux%20Libraries/iup-3.30_Linux44_64_lib.tar.gz'
    - IUP_BIONIC_URL='https://master.dl.sourceforge.net/project/iup/3.29/Linux%20Libraries/iup-3.29_Linux415_64_lib.tar.gz'
    - IUP_FOCAL_URL='https://deac-ams.dl.sourceforge.net/project/iup/3.30/Linux%20Libraries/iup-3.30_Linux54_64_lib.tar.gz'

git:
  depth: 1

matrix:
  fast_finish: false
  include:

  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        packages:
          - libpcap-dev
    before_install:
      - mkdir /tmp/iup
      - cd /tmp/iup
      - wget $IUP_XENIAL_URL -O /tmp/iup/iup.tar.gz
      - tar -xvf /tmp/iup/iup.tar.gz
      - printf '\n' | sudo ./install
      - printf '\n' | sudo ./install_dev
      - cd $TRAVIS_BUILD_DIR
    script: make

  - os: linux
    dist: bionic
    compiler: gcc
    addons:
      apt:
        packages:
          - libpcap-dev
      coverity_scan:
        project:
          name: homewsn/bsniffhub
          description: Build submitted via Travis CI
        notification_email: homewsn.com@gmail.com
        build_command_prepend: cov-configure --comptype gcc --compiler /usr/bin/gcc
        build_command: make
        branch_pattern: master
    before_install:
      - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      - mkdir /tmp/iup
      - cd /tmp/iup
      - wget $IUP_BIONIC_URL -O /tmp/iup/iup.tar.gz
      - tar -xvf /tmp/iup/iup.tar.gz
      - printf '\n' | sudo ./install
      - printf '\n' | sudo ./install_dev
      - cd $TRAVIS_BUILD_DIR
    script: make

  - os: linux
    dist: focal
    compiler: gcc
    addons:
      apt:
        packages:
          - libpcap-dev
    before_install:
      - mkdir /tmp/iup
      - cd /tmp/iup
      - wget $IUP_FOCAL_URL -O /tmp/iup/iup.tar.gz
      - tar -xvf /tmp/iup/iup.tar.gz
      - printf '\n' | sudo ./install
      - printf '\n' | sudo ./install_dev
      - cd $TRAVIS_BUILD_DIR
    script: make

  - os: linux
    dist: focal
    compiler: clang
    addons:
      apt:
        packages:
          - libpcap-dev
    script: make bsniffhub

  - os: osx
    compiler: clang
    addons:
      homebrew:
        packages:
          - libpcap-dev
    script: make bsniffhub
