language: c

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "LfzrsekJOA4cP/zJaeLtj1o4ZKiFSiJpHGGHIQ9CHJqQZysx3Fe2hI5WNcb2p7zENe1+6PI6SfC2choX8dXgrdrsPiz4TULVmKhdQVDctLtlOIPLfI+nW9/dCDLRnQJ3+/fXP3CLlA0FqZ54loCWLQZWPOZUYZAu1DxliOp67Tm/rfVkX/c6eV9pxuaOPLD/k22kX1xas3Cg7s3IwWuKB03TDd2n5/TXlKBAHZ0KkjBW7TytZr/rjxDDUnEhSufv7hw0z7Mdyll5ZfD90TxLiieeEBBEBe7uQcknL+soqryJlXxfV+BsXh214NQvnOMysq7o6kztQh2ORXQcTUetVi161Wextq0ZbWa4jEIH8HTnb7YkyKKG91GzxITfTBis5tuZXgWnek1Aut+Z7Crd8XmpjsRhJB2bzZq9XUeO5GrL/UtmGO9190s4M8wTjAYA6a727hYC+VkNk/X5gOhmOtAKz061PhAwDfzhQeyMnFlwvLPHAsLz7r4AwlQbpfYpufCdZeYU7DYH4CF8nFwELVfPQdCcayXrfIZ2HdWX17P4Na6NmraUrcks0r6Ts6nXFaW1XgsVJcybRejijK0AyOQaXerhEEXoOpXyyaK/vTC599t8yldwPziL2jAXUzYolZ5bhBizS90KttAt3xK0+qex+LOK09cAR7s4rL/ZA4g="
    # IUP packages
    # Linux44_64: xenial (x64) gcc 5.3
    # Linux415_64: bionic (x64) gcc 7.3
    # Linux54_64: focal (x64) gcc 9.3
    - IUP_XENIAL_URL='https://netactuate.dl.sourceforge.net/project/iup/3.30/Linux%20Libraries/iup-3.30_Linux44_64_lib.tar.gz'
    - IUP_BIONIC_URL='https://master.dl.sourceforge.net/project/iup/3.29/Linux%20Libraries/iup-3.29_Linux415_64_lib.tar.gz'
    - IUP_FOCAL_URL='https://deac-ams.dl.sourceforge.net/project/iup/3.30/Linux%20Libraries/iup-3.30_Linux54_64_lib.tar.gz'

git:
  depth: 1

matrix:
  fast_finish: false
  include:

  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        packages:
          - libpcap-dev
    before_install:
      - mkdir /tmp/iup
      - cd /tmp/iup
      - wget $IUP_XENIAL_URL -O /tmp/iup/iup.tar.gz
      - tar -xvf /tmp/iup/iup.tar.gz
      - printf '\n' | sudo ./install
      - printf '\n' | sudo ./install_dev
      - cd $TRAVIS_BUILD_DIR
    script: make

  - os: linux
    dist: bionic
    compiler: gcc
    addons:
      apt:
        packages:
          - libpcap-dev
      coverity_scan:
        project:
          name: homewsn/bsniffhub
          description: Build submitted via Travis CI
        notification_email: homewsn.com@gmail.com
        build_command_prepend: cov-configure --comptype gcc --compiler /usr/bin/gcc
        build_command: make
        branch_pattern: master
    before_install:
      - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      - mkdir /tmp/iup
      - cd /tmp/iup
      - wget $IUP_BIONIC_URL -O /tmp/iup/iup.tar.gz
      - tar -xvf /tmp/iup/iup.tar.gz
      - printf '\n' | sudo ./install
      - printf '\n' | sudo ./install_dev
      - cd $TRAVIS_BUILD_DIR
    script: make

  - os: linux
    dist: focal
    compiler: gcc
    addons:
      apt:
        packages:
          - libpcap-dev
    before_install:
      - mkdir /tmp/iup
      - cd /tmp/iup
      - wget $IUP_FOCAL_URL -O /tmp/iup/iup.tar.gz
      - tar -xvf /tmp/iup/iup.tar.gz
      - printf '\n' | sudo ./install
      - printf '\n' | sudo ./install_dev
      - cd $TRAVIS_BUILD_DIR
    script: make

  - os: linux
    dist: focal
    compiler: clang
    addons:
      apt:
        packages:
          - libpcap-dev
    script: make bsniffhub

  - os: osx
    compiler: clang
    addons:
      homebrew:
        packages:
          - libpcap-dev
    script: make bsniffhub
