MODULE_SRCDIR   := $(SRCDIR)/cli
MODULE_HDRDIR   := $(SRCDIR)/cli
MODULE_INCLPATH := $(SRCDIR)/cli

MODULE_SOURCES  := $(wildcard $(MODULE_SRCDIR)/*.c)
MODULE_HEADERS  := $(wildcard $(MODULE_HDRDIR)/*.h)

OBJECTS_CLI  := $(MODULE_SOURCES:$(MODULE_SRCDIR)/%.c=$(OBJDIR_CLI)/%.o)
SRCDIR_CLI   := $(MODULE_SRCDIR)
DEPS_CLI     := $(MODULE_HEADERS)
INCLPATH_CLI := -I$(MODULE_INCLPATH)
