name: build

on:
  push:
    branches: [ master, github-ci ]
    paths-ignore:
      - '**.md'
      - 'examples/**'
  pull_request:
    branches: [ master, github-ci ]
    paths-ignore:
      - '**.md'
      - 'examples/**'
  workflow_dispatch:

jobs:

  Coverity-Scan-gcc:
    runs-on: ubuntu-22.04
    env:
      # URLs
      IUP_22_URL: https://master.dl.sourceforge.net/project/iup/3.32/Linux%20Libraries/iup-3.32_Linux515_64_lib.tar.gz?viasf=1
      COV_SCAN_URL: https://scan.coverity.com/download/cxx/linux64
      # Compiler
      CC: gcc
    steps:
    - uses: actions/checkout@v4
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libpcap-dev
    - name: Download and install IUP
      run: |
        mkdir /tmp/iup
        #wget $IUP_BIONIC_URL -O /tmp/iup/iup.tar.gz
        wget $IUP_22_URL -O /tmp/iup/iup.tar.gz
        tar -xvf /tmp/iup/iup.tar.gz
        printf '\n' | sudo ./install
        printf '\n' | sudo ./install_dev
    - name: Download and untar Coverity Scan
      run: |
        mkdir /tmp/synopsys
        wget -nv $COV_SCAN_URL --post-data "token=${{ secrets.COVERITY_SCAN_TOKEN }}&project=homewsn%2Fbsniffhub" -O /tmp/synopsys/cov_scan.tar.gz
        # Untar to /tmp/synopsys/cov_scan directory
        mkdir /tmp/synopsys/cov_scan
        tar --totals -x -f /tmp/synopsys/cov_scan.tar.gz --strip 1 -C /tmp/synopsys/cov_scan
    - name: Coverity Scan Build
      run: |
        export PATH=$PATH:/tmp/synopsys/cov_scan/bin
        cov-configure --comptype gcc --compiler /usr/bin/gcc
        cov-build --dir cov-int make
    - name: Submit results to Coverity Scan
      run: |
        tar -czvf cov-int.tgz cov-int
        short_git_hash=$(git rev-parse --short "$GITHUB_SHA")
        curl \
          --form token="${{ secrets.COVERITY_SCAN_TOKEN }}" \
          --form email="homewsn.com@gmail.com" \
          --form file=@cov-int.tgz \
          --form version=$short_git_hash \
          --form description="Build submitted via Github Actions" \
          "https://scan.coverity.com/builds?project=homewsn%2Fbsniffhub"
#    - name: Build
#      run: make

  Ubuntu-22-gcc:
    runs-on: ubuntu-22.04
    env:
      # URLs
      IUP_22_URL: https://master.dl.sourceforge.net/project/iup/3.32/Linux%20Libraries/iup-3.32_Linux515_64_lib.tar.gz?viasf=1
      # Compiler
      CC: gcc
    steps:
    - uses: actions/checkout@v4
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libpcap-dev
    - name: Before Build
      run: |
        mkdir /tmp/iup
        wget $IUP_22_URL -O /tmp/iup/iup.tar.gz
        tar -xvf /tmp/iup/iup.tar.gz
        printf '\n' | sudo ./install
        printf '\n' | sudo ./install_dev
    - name: Build
      run: make

  Ubuntu-24-gcc:
    runs-on: ubuntu-24.04
    env:
      # URLs
      IUP_24_URL: https://master.dl.sourceforge.net/project/iup/3.32/Linux%20Libraries/iup-3.32_Linux68_64_lib.tar.gz?viasf=1
      # Compiler
      CC: gcc
    steps:
    - uses: actions/checkout@v4
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libpcap-dev
    - name: Before Build
      run: |
        mkdir /tmp/iup
        wget $IUP_24_URL -O /tmp/iup/iup.tar.gz
        tar -xvf /tmp/iup/iup.tar.gz
        printf '\n' | sudo ./install
        printf '\n' | sudo ./install_dev
    - name: Build
      run: make

  Ubuntu-Latest-clang:
    runs-on: ubuntu-latest
    env:
      # Compiler
      CC: clang
    steps:
    - uses: actions/checkout@v4
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libpcap-dev
    - name: Build
      run: make bsniffhub

  MacOS-Latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Packages
      run: |
        brew update
        brew install libpcap
    - name: Build
      run: make bsniffhub
  
  Windows-2022-vc2017:
    runs-on: windows-2022
    env:
      # URLs
      npcap_url: https://nmap.org/npcap/dist/npcap-sdk-1.06.zip
      # Folders
      npcap_dir: ${{ github.workspace }}\msvs\lib\npcap
      sln_dir: ${{ github.workspace }}\msvs
    steps:
    - uses: actions/checkout@v4
    - name: Install Msbuild
      uses: microsoft/setup-msbuild@v2
    - name: Download vs_buildtools.exe
      run: Invoke-webrequest -uri  https://aka.ms/vs/15/release/vs_buildtools.exe -OutFile vs_buildtools.exe
      shell: powershell
    - name: Install VS 2017 Build Tools
      run: .\vs_buildtools.exe --add Microsoft.VisualStudio.Workload.MSBuildTools --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --quiet --wait --norestart --force
      shell: cmd
    - name: Before Build
      run: |
        (New-Object Net.WebClient).DownloadFile("${{ env.npcap_url }}", "${{ env.npcap_dir }}\npcap.zip")
        7z x ${{ env.npcap_dir }}\npcap.zip -y -o${{ env.npcap_dir }}
    - name: Build x64
      run: msbuild ${{ env.sln_dir }}\bsniffhub.sln /p:configuration=Release /p:platform=x64 /p:PlatformToolset=v141
    - name: Build x86
      run: msbuild ${{ env.sln_dir }}\bsniffhub.sln /p:configuration=Release /p:platform=x86 /p:PlatformToolset=v141