name: build

on:
  push:
    branches: [ master, github-ci ]
    paths-ignore:
      - '**.md'
      - 'examples/**'
  pull_request:
    branches: [ master, github-ci ]
    paths-ignore:
      - '**.md'
      - 'examples/**'
  workflow_dispatch:

jobs:

  Ubuntu-Bionic-gcc:
    runs-on: ubuntu-18.04
    env:
      # URLs
      IUP_BIONIC_URL: https://master.dl.sourceforge.net/project/iup/3.29/Linux%20Libraries/iup-3.29_Linux415_64_lib.tar.gz
      COV_SCAN_URL: https://scan.coverity.com/download/cxx/linux64
      # Compiler
      CC: gcc
    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libpcap-dev
    - name: Download and install IUP
      run: |
        mkdir /tmp/iup
        wget $IUP_BIONIC_URL -O /tmp/iup/iup.tar.gz
        tar -xvf /tmp/iup/iup.tar.gz
        printf '\n' | sudo ./install
        printf '\n' | sudo ./install_dev
    - name: Download and untar Coverity Scan
      run: |
        mkdir /tmp/synopsys
        wget -nv $COV_SCAN_URL --post-data "token=${{ secrets.COVERITY_SCAN_TOKEN }}&project=homewsn%2Fbsniffhub" -O /tmp/synopsys/cov_scan.tar.gz
        # Untar to /tmp/synopsys/cov_scan directory
        mkdir /tmp/synopsys/cov_scan
        tar --totals -x -f /tmp/synopsys/cov_scan.tar.gz --strip 1 -C /tmp/synopsys/cov_scan
    - name: Coverity Scan Build
      run: |
        export PATH=$PATH:/tmp/synopsys/cov_scan/bin
        cov-configure --comptype gcc --compiler /usr/bin/gcc
        cov-build --dir cov-int make
    - name: Submit results to Coverity Scan
      run: |
        tar -czvf cov-int.tgz cov-int
        short_git_hash=$(git rev-parse --short "$GITHUB_SHA")
        curl \
          --form token="${{ secrets.COVERITY_SCAN_TOKEN }}" \
          --form email="homewsn.com@gmail.com" \
          --form file=@cov-int.tgz \
          --form version=$short_git_hash \
          --form description="Build submitted via Github Actions" \
          "https://scan.coverity.com/builds?project=homewsn%2Fbsniffhub"
    - name: Build
      run: make
