name: build

on:
  push:
    branches: [ master, github-ci ]
    paths-ignore: '**.md'
  pull_request:
    branches: [ master, github-ci ]
    paths-ignore: '**.md'
  workflow_dispatch:

jobs:

  Ubuntu-Bionic-gcc:
    runs-on: ubuntu-18.04
    env:
      # URLs
      IUP_BIONIC_URL: https://master.dl.sourceforge.net/project/iup/3.29/Linux%20Libraries/iup-3.29_Linux415_64_lib.tar.gz
      COV_SCAN_URL: https://scan.coverity.com/download/cxx/linux64
      # Compiler
      CC: gcc
    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        echo git_hash
        echo $git_hash
