name: build

on:
  push:
    branches: [ master, github-ci ]
    paths-ignore: '**.md'
  pull_request:
    branches: [ master, github-ci ]
    paths-ignore: '**.md'
  workflow_dispatch:

jobs:

  Ubuntu-Bionic-gcc:
    runs-on: ubuntu-18.04
    env:
      # URLs
      IUP_BIONIC_URL: https://master.dl.sourceforge.net/project/iup/3.29/Linux%20Libraries/iup-3.29_Linux415_64_lib.tar.gz
      COV_SCAN_URL: https://scan.coverity.com/download/cxx/linux64
      # Compiler
      CC: gcc
    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libpcap-dev
    - name: Before Build
      run: |
        mkdir /tmp/iup
        wget $IUP_BIONIC_URL -O /tmp/iup/iup.tar.gz
        tar -xvf /tmp/iup/iup.tar.gz
        printf '\n' | sudo ./install
        printf '\n' | sudo ./install_dev
    - name: Install Coverity Scan
      run: |
        mkdir /tmp/synopsys
        wget -nv $COV_SCAN_URL --post-data "token=${{ secrets.COVERITY_SCAN_TOKEN }}&project=homewsn%2Fbsniffhub" -O /tmp/synopsys/cov_scan.tar.gz
        # Untar to /tmp/synopsys/cov_scan directory
        tar --totals -x -f /tmp/synopsys/cov_scan.tar.gz --transform 's!^[^/]\+\($\|/\)!cov_scan\1!'
        export PATH=$PATH:/tmp/synopsys/cov_scan/bin/
    - name: Coverity Scan Build
      run: cov-build --dir cov-int make
    - name: Build
      run: make
